tasks/urls.py
from django.urls import path
from . import views

app_name = 'tasks'

urlpatterns = [
    path('', views.homepage, name='index'),
    path('add_task/', views.add_task, name='add_task'),
    path('tasklist/', views.task_list, name='tasklist'),
    path('edit_task/<int:task_id>/', views.edit_task, name='edit_task'),
    path('delete_task/<int:task_id>/', views.delete_task, name='delete_task'),
    path('update_task_completion/', views.update_task_completion, name='update_task_completion'),
    path('calendar/', views.calendar_view, name='calendar'),
    path('events/', views.load_events, name='load_events'),
    
]

todoapp/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('',views.login_page, name='login'),
    path('signup/', views.signup_page, name='signup'),
    path('index/', views.homepage, name='index'),
    
    path('logout/', views.logout_view, name='logout'),
   
]

todolist/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todoapp.urls')),
    path('tasks/', include('tasks.urls', namespace='tasks')),
]

tasks/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Task(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True) 
    title = models.CharField(max_length=200)
    description = models.TextField()
    completed = models.BooleanField(default=False)
    due_date = models.DateTimeField(null=True, blank=True)
    due_datetime = models.DateTimeField(blank=True, null=True) 

    def __str__(self):
        return self.title



class Event(models.Model):
    title = models.CharField(max_length=200)
    start_datetime = models.DateTimeField()
    end_datetime = models.DateTimeField()

    def __str__(self):
        return self.title

# Create your models here.

todoapp/models.py
from django.db import models

# class Task(models.Model):
#     title = models.CharField(max_length=200)
#     description = models.TextField()
#     completed = models.BooleanField(default=False)

#     def __str__(self):
#         return self.title

# Create your models here.

tasks/forms.py
from django import forms
from .models import Task

class TaskForm(forms.ModelForm):
    due_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    due_time = forms.TimeField(widget=forms.TimeInput(attrs={'type': 'time'}))

    class Meta:
        model = Task
        fields = ['title', 'description', 'completed', 'due_date', 'due_time']

tasks/views.py
from django.shortcuts import render, redirect
from .models import Task
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .forms import TaskForm
from datetime import date, timedelta
from .models import Event
from datetime import datetime
from django.utils.timezone import make_aware
from django.utils import timezone
from django.db.models import Q
from django.utils.safestring import mark_safe
from django.urls import reverse_lazy
import calendar
from django.contrib.auth.decorators import login_required

@login_required(login_url='login')
def homepage(request):
    tasks = Task.objects.all()
    context = {'tasks': tasks}
    return render(request, 'index.html', context)



def add_task(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.owner = request.user
            due_date = form.cleaned_data['due_date']
            due_time = form.cleaned_data['due_time']
            due_datetime = datetime.combine(due_date, due_time)
            task.due_datetime = make_aware(due_datetime)
            task.save()
            return redirect('tasks:tasklist')
    else:
        form = TaskForm()
    return render(request, 'index.html', {'form': form})




def task_list(request):
    tasks = Task.objects.filter(owner=request.user)
    search_query = request.GET.get('search')
    new_tasks = Task.objects.filter(completed=False)
    completed_tasks = Task.objects.filter(completed=True)
    current_datetime = timezone.now()

    for task in new_tasks:
        if task.due_datetime:
            remaining_time = task.due_datetime - current_datetime
            task.remaining_time = remaining_time
        else:
            task.remaining_time = None

    if search_query:
        new_tasks = new_tasks.filter(Q(title__icontains=search_query) | Q(description__icontains=search_query))
        completed_tasks = completed_tasks.filter(Q(title__icontains=search_query) | Q(description__icontains=search_query))

    context = {
        'new_tasks': new_tasks,
        'completed_tasks': completed_tasks
    }
    return render(request, 'tasklist.html', context)



def edit_task(request, task_id):
    task = Task.objects.get(pk=task_id)
    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            task = form.save(commit=False)
            due_date = form.cleaned_data['due_date']
            due_time = form.cleaned_data['due_time']
            due_datetime = datetime.combine(due_date, due_time)
            task.due_datetime = make_aware(due_datetime)
            task.save()
            return redirect('tasks:tasklist')
    else:
        form = TaskForm(instance=task)
    return render(request, 'edit_task.html', {'form': form, 'task': task})





def delete_task(request, task_id):
    task = Task.objects.get(pk=task_id)
    if request.method == 'POST':
        task.delete()
        return redirect('tasks:tasklist')
    
    context = {'task': task}
    return render(request, 'delete_task.html', context)

def update_task_completion(request):
    if request.method == 'POST' and request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        task_id = request.POST.get('task_id')
        completed = request.POST.get('completed') == 'true'
        
        # Update the task completion status in the database
        
        return JsonResponse({'message': 'Task completion status updated successfully.'})
    else:
        return JsonResponse({'error': 'Invalid request.'}, status=400)

def calendar_view(request):
    # Get the current date
    today = date.today()

    # Calculate the start and end dates for the calendar view
    start_date = today - timedelta(days=today.weekday())
    end_date = start_date + timedelta(days=6)

    # Generate a list of dates within the range
    calendar_dates = []
    current_date = start_date
    while current_date <= end_date:
        calendar_dates.append(current_date)
        current_date += timedelta(days=1)

    # Retrieve the tasks for the calendar view
    tasks = Task.objects.filter(due_date__range=[start_date, end_date])

    return render(request, 'calendar.html', {'dates': calendar_dates, 'tasks': tasks})



def load_events(request):
    events = Event.objects.all()
    data = []
    for event in events:
        data.append({
            'title': event.title,
            'start': event.start_datetime.isoformat(),
            'end': event.end_datetime.isoformat(),
        })
    return JsonResponse(data, safe=False)

todoapp/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

 


@login_required(login_url='login')
def homepage(request):
     return render(request,'index.html')


def login_page(request):
    if request.method=='POST':
        username=request.POST.get('username')
        pass1=request.POST.get('pass')
        user=authenticate(request,username=username,password=pass1)
        if user is not None:
            login(request,user)
            return redirect('index')
        else:
            return HttpResponse("username or password is incorrect !!")



    return render(request, 'login.html')
    


def signup_page(request):
    if request.method=='POST':
        uname=request.POST.get('username')
        email=request.POST.get('email')
        pass1=request.POST.get('password')
        my_user=User.objects.create_user(uname,email,pass1)
        my_user.save()
        return redirect('index')


    return render(request, 'signup.html')






def logout_view(request):
    logout(request)
    return render(request, 'login.html')

tasks/templates/add_task.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<h1>Welcome back</h1>
<head>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<div class="addtask-box">
  <form method="POST" action="{% url 'tasks:add_task' %}">
      {% csrf_token %}
      <h2> Write task here</h2>
      <label for="Title">Title:</label>
      <input type="text"name="title" required>
      <label for="description">Discription:</label>
      <input type="text" name="description" required>
      <label for="due_date">Due Date:</label>
      <input type="date" id="due_date" name="due_date" required>
      <br>
      <label for="due_time">Due Time:</label>
      <input type="time" id="due_time" name="due_time" required>
      <br>
      <button type="submit">Add Task</button>
  </form>
</div>
{% endblock %}

tasks/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" type="text/css" href="{%  static 'base.css' %}">
   

    <title>TO DO LIST</title>
  </head>
  <body>
   
      <nav>
        <h1>Todo List</h1>
        <ul>
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'tasks:tasklist' %}">My Tasks</a></li>
          <li><a href="{% url 'tasks:calendar' %}">Calendar</a></li>
          

          <li class="dropdown">
            <a href="#" class="dropdown-toggle">-Task-<i class="fas fa-chevron-down"></i></a>
            <div class="dropdown-content">
              <a href="#new-tasks">New</a>
              <a href="#completed-tasks">Completed</a>
              <a href="{% url 'logout' %}">Logout</a>
            </div>
          </li>

          
        </ul>

      </nav>
      {% block content %}

  
      {% endblock %}


  </body>
</html>

tasks/templates/calendar.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
 


<!DOCTYPE html>
<html>
<head>
    <title>Calendar</title>
    <link rel="stylesheet" href="{% static 'calendar.css' %}" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.2/fullcalendar.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.2/fullcalendar.min.js"></script>
</head>
<body>
    <div id="calendar"></div>
    {% for date in dates %}
       <div class="date">{{ date }}</div>
       {% for task in tasks %}
           {% if task.due_date == date %}
               <div class="task">{{ task.title }}</div>
           {% endif %}
       {% endfor %}
        
    {% endfor %}
    <script>
        $(document).ready(function() {
            $('#calendar').fullCalendar({
                header: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'month,agendaWeek,agendaDay'
                },
                defaultView: 'month',
                editable: true,
                events: [
                    // Add your event data here
                    {
                        title: 'Event 1',
                        start: '2023-05-01'
                    },
                    {
                        title: 'Event 2',
                        start: '2023-05-10',
                        end: '2023-05-12'
                    }
                ],
                events: function(start, end, timezone, callback) {
                    // Fetch events from an API endpoint or database
                    $.ajax({
                        url: '/api/events',
                        dataType: 'json',
                        success: function(data) {
                            // Process the fetched event data
                            var events = [];
                            for (var i = 0; i < data.length; i++) {
                                events.push({
                                    title: data[i].title,
                                    start: data[i].start,
                                    end: data[i].end
                                });
                            }
                            // Pass the processed event data to the calendar
                            callback(events);
                        }
                    });
                }
            });
        });
    </script>
</body>
</html>

{% endblock %}

tasks/templates/delete_task.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>Delete Task</title>
  <link rel="stylesheet" type="text/css" href="{%  static 'edit_delete.css' %}">
</head>
<body>
  <h1>Delete Task</h1>
  

  <form method="post" action="{% url 'tasks:delete_task' task.id %}">
    {% csrf_token %}
    <p>Are you sure you want to delete the task "{{ task.title }}"?</p>
    <button type="submit">Delete</button>
    <a href="{% url 'tasks:tasklist' %}">Cancel</a>
  </form>
</body>
</html>

tasks/templates/edit_task.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>Edit Task</title>
  <link rel="stylesheet" type="text/css" href="{% static 'edit_delete.css' %}">
</head>
<body>
  <h1>Edit Task</h1>
  

  <form method="post" action="{% url 'tasks:edit_task' task.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    
    <button type="submit">Save</button>
    <a href="{% url 'tasks:tasklist' %}">Cancel</a>
  </form>
</body>
</html>

tasks/templates/task_list.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
    <h1>My To-Do List App</h1>
    <link rel="stylesheet" href="{% static 'tasks.css' %}">

    <a href="{% url 'tasks:add_task' %}">Add Task</a>
    <ul>
        {% for task in tasks %}
            <li>
                <input type="checkbox" {% if task.completed %}checked{% endif %}>
                <strong>{{ task.title }}</strong>
                <p>{{ task.description }}</p>
            </li>
        {% empty %}
            <li>No tasks yet.</li>
        {% endfor %}
    </ul>
{% endblock %}

tasks/templates/tasklist.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h1>My To-Do List</h1>
    <link rel="stylesheet" href="{% static 'tasks.css' %}">
    
    <form action="{% url 'tasks:tasklist' %}" method="GET">
        <input type="text" name="search" placeholder="Search tasks">
        <button type="submit">Search</button>
    </form>
    <div class="final">
        <h2 id="new-tasks">New Tasks</h2>
        <div id="new-tasks-container">
            {% for task in new_tasks %}
                {% if not task.completed %}
                    <div class="task-item">
                        <div class="titlee">
                            <input type="checkbox" id="task-{{ task.id }}-checkbox" {% if task.completed %}checked{% endif %} onchange="toggleTaskCompletion({{ task.id }})">
                            <strong>{{ task.title }}</strong>
                        </div>
                        <p>{{ task.description }}</p>
                        <div class="date-time">
                            <p>Due Date: {{ task.due_date }}</p>
                            <p>Remaining Time: {{ task.remaining_time }}</p>   
                        </div>
                        <div class="edit-delete-btns">
                            <button class="edit-button" onclick="location.href='{% url 'tasks:edit_task' task.id %}'">Edit</button>
                            <button class="delete-button" onclick="location.href='{% url 'tasks:delete_task' task.id %}'">Delete</button>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    
        <h2 id="completed-tasks">Completed Tasks</h2>
        <div id="completed-tasks-container">
            {% for task in completed_tasks %}
                {% if task.completed %}
                    <div class="task-item">
                        <div class="titlee">
                            <input type="checkbox" id="task-{{ task.id }}-checkbox" {% if task.completed %}checked{% endif %} onchange="toggleTaskCompletion({{ task.id }})">
                            <strong>{{ task.title }}</strong>
                        </div>
                        <p>{{ task.description }}</p>
                        <div class="date-time">
                            <p>Due Date: {{ task.due_date }}</p>
                            <p>Remaining Time: {{ task.remaining_time }}</p>   
                        </div>
                        <div class="edit-delete-btns">
                            <button class="edit-button" onclick="location.href='{% url 'tasks:edit_task' task.id %}'">Edit</button>
                            <button class="delete-button" onclick="location.href='{% url 'tasks:delete_task' task.id %}'">Delete</button>
                        </div>   
                    </div>
                {% endif %}
            {% endfor %}
        </div> 


    </div>
 
    

    {% load static %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <script>
        function toggleTaskCompletion(taskId) {
            var isChecked = $('#task-' + taskId + '-checkbox').is(':checked');
            var taskContainer = isChecked ? $('#completed-tasks-container') : $('#new-tasks-container');
            var taskItem = $('#task-' + taskId + '-checkbox').closest('.task-item');

            // Move the task item to the appropriate container
            taskContainer.append(taskItem);

            // Send AJAX request to update the task completion status
            $.ajax({
                type: 'POST',
                url: '{% url 'tasks:update_task_completion' %}',
                data: {
                    task_id: taskId,
                    completed: isChecked ? 'true' : 'false',
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                success: function(response) {
                    // Handle the response if needed
                },
                error: function(xhr, textStatus, error) {
                    // Handle the error if needed
                }
            });
        }
    </script>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<h1>Welcome back</h1>
<head>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<div class="addtask-box">
  <form method="POST" action="{% url 'tasks:add_task' %}">
      {% csrf_token %}
      <h2> Write task here</h2>
      <label for="Title">Title:</label>
      <input type="text"name="title" required>
      <label for="description">Discription:</label>
      <input type="text" name="description" required>
      <label for="due_date">Due Date:</label>
      <input type="date" id="due_date" name="due_date" required>
      <br>
      <label for="due_time">Due Time:</label>
      <input type="time" id="due_time" name="due_time" required>
      <br>
      <button type="submit">Add Task</button>
  </form>
</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<h1>Welcome back</h1>
<head>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<div class="addtask-box">
  <form method="POST" action="{% url 'tasks:add_task' %}">
      {% csrf_token %}
      <h2> Write task here</h2>
      <label for="Title">Title:</label>
      <input type="text"name="title" required>
      <label for="description">Discription:</label>
      <input type="text" name="description" required>
      <label for="due_date">Due Date:</label>
      <input type="date" id="due_date" name="due_date" required>
      <br>
      <label for="due_time">Due Time:</label>
      <input type="time" id="due_time" name="due_time" required>
      <br>
      <button type="submit">Add Task</button>
  </form>
</div>
{% endblock %}

templates/index.html.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<h1>Welcome back</h1>
<head>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<div class="addtask-box">
  <form method="POST" action="{% url 'tasks:add_task' %}">
      {% csrf_token %}
      <h2> Write task here</h2>
      <label for="Title">Title:</label>
      <input type="text"name="title" required>
      <label for="description">Discription:</label>
      <input type="text" name="description" required>
      <label for="due_date">Due Date:</label>
      <input type="date" id="due_date" name="due_date" required>
      <br>
      <label for="due_time">Due Time:</label>
      <input type="time" id="due_time" name="due_time" required>
      <br>
      <button type="submit">Add Task</button>
  </form>
</div>
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html>
<head>
	
	<title>TO DO LIST</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'bluestyle.css' %}">
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	
	
</head>
<body>
	<h1>TO DO LIST</h1>
    <div class="loginbox">
      
	  <h2>log in</h2>
	  <form method="post">
		{% csrf_token %}
		<p>Username</p>
		<input type="text" name="username" placeholder="Enter Username">
		<p>password</p>
		<input type="password" name="pass" placeholder="Enter password">
		
		<input type="submit" name="" value="login">
		<p>Don't have an account ?</p>
	    <a href="{% url 'signup' %}">create an account </a>
	  </form>

    </div>
    
	

</body>
</html>

templates/logout.html
{% extends 'base.html' %}

{% block content %}
  <h1>Logout</h1>
  <p>You sure you want to log out?</p>

  <form method="post" action="{% url 'logout' %}">
    {% csrf_token %}
    <button type="submit">Logout</button>
  </form>
{% endblock %}

templates/signup.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Sign Up Page</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'sign-up-styles.css' %}">
</head>
<body>
 <div class="sign-up-page">
        <!-- <img src="images/icon.jpg"> -->
    <h1>Sign Up Now</h1>
    <form action="" method="post">
        {% csrf_token %}
        <p>Email</p>
        <input type="email" name="email" placeholder="Enter your email">
        <p>Username</p>
        <input type="text" name="username" placeholder="Enter Username">
        <p>Password</p>
        <input type="password" name="password" placeholder="Enter your password">
        <p><span><input type="checkbox"></span> agree to the terms and conditions </p>
        <button type="submit" class="signup-btn">Sign up</button>
        <hr>
        <p class="or">OR</p>
        <button type="button" class="facebook-btn">Login with Facebook</button>
        <p>You already have an account ? <a href="{% url 'login' %}">Login</a></p>
    </form>
 </div>
</body>
</html>